spring.application.name=KodikaraGroupBusinessManagementApplication
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/KODIKARA_BAKERS
spring.datasource.username=root
spring.datasource.password=@12Chem$|eRS
spring.datasources.driver-class-name=com.mysql.cj.jdbc.Driver
sprinf.jpa.show-sql=true
